- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes
      become_user: root

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes
      become_user: root

    - name: Stop and remove any existing container using port 8084
      shell: |
        container_id=$(docker ps --filter "publish=8084" --format "{{.ID}}")
        if [ ! -z "$container_id" ]; then
          docker stop "$container_id" && docker rm "$container_id"
        fi
      ignore_errors: yes

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 dhananjay6736/insure-me:3.0
